// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATRyj5YxX6EoDH_rBtnsBvu5oukFENR_o',
    appId: '1:586829444224:web:791107fc0295c4b96be265',
    messagingSenderId: '586829444224',
    projectId: 'authentificationproject-c6103',
    authDomain: 'authentificationproject-c6103.firebaseapp.com',
    storageBucket: 'authentificationproject-c6103.appspot.com',
    measurementId: 'G-BN68BZPCDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKBj-q-iPMCnw3I858AboHU2znWK4cI1U',
    appId: '1:586829444224:android:11d776e046069a9e6be265',
    messagingSenderId: '586829444224',
    projectId: 'authentificationproject-c6103',
    storageBucket: 'authentificationproject-c6103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO_waMWkIDf_wKMrLE405nqZirbKHzsIs',
    appId: '1:586829444224:ios:b9464ef62bb8a1b76be265',
    messagingSenderId: '586829444224',
    projectId: 'authentificationproject-c6103',
    storageBucket: 'authentificationproject-c6103.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATRyj5YxX6EoDH_rBtnsBvu5oukFENR_o',
    appId: '1:586829444224:web:197552270cd8b2396be265',
    messagingSenderId: '586829444224',
    projectId: 'authentificationproject-c6103',
    authDomain: 'authentificationproject-c6103.firebaseapp.com',
    storageBucket: 'authentificationproject-c6103.appspot.com',
    measurementId: 'G-DCLX64S23W',
  );
}
